// ─── LEGAL DOCUMENTS + CONSENT UI ────────────────────────────────────────────
// Embedded Terms of Service / Liability Waiver and Privacy Policy, plus the
// full-screen consent flow shown at athlete signup. The text below is the
// verbatim "Last Updated: June 1, 2026" version of the documents hosted at
// trainwilco.com/terms and trainwilco.com/privacy.
//
// KEEP IN SYNC: when the hosted documents change, update both the text constants
// below AND LEGAL_VERSION. LEGAL_VERSION is written into the legal_acceptances
// table on signup so we have an auditable record of which version each athlete
// agreed to.
import React, { useState } from "react";

export const LEGAL_VERSION = "2026-06-01";

export const TERMS_TEXT = `WILCO TRAINING LLC
Terms of Service and Liability Waiver
Effective Date: May 22, 2026  |  Last Updated: June 1, 2026
BY CHECKING THE BOX AND CREATING AN ACCOUNT, YOU AGREE TO THESE TERMS AND THE LIABILITY WAIVER CONTAINED HEREIN. IF YOU DO NOT AGREE, DO NOT USE THE PLATFORM.
1. Agreement to Terms
By accessing or using the Wilco Training platform (“Platform”), you agree to be bound by these Terms of Service and Liability Waiver (“Terms”). These Terms constitute a legally binding agreement between you and Wilco Training LLC. If you are between 13 and 17 years of age, your parent or legal guardian must review and agree to these Terms on your behalf before you use the Platform. If you do not agree to these Terms in their entirety, you must not use the Platform.
2. About Us
Wilco Training LLC is a Florida limited liability company (“Wilco,” “we,” “us,” or “our”) with its principal place of business at 801 International Pkwy, Suite #5034, Lake Mary, Florida 32746. The Platform is operated at TrainWilco.com. For inquiries, contact us at support@trainwilco.com.
3. Eligibility and Age Requirement
You must be at least 13 years of age to use the Platform. By creating an account, you represent and warrant that:
You are at least 13 years old;
If you are between 13 and 17 years old, your parent or legal guardian has reviewed, understood, and agreed to these Terms on your behalf before account creation; and
All information you provide during registration is truthful, accurate, and complete.
Wilco does not knowingly permit users under the age of 13 to access the Platform. If we determine that a user is under 13, we will immediately terminate that account and permanently delete all associated data.
4. Description of Services
Wilco provides an AI-powered strength and conditioning platform designed to help high school athletes improve athletic performance through personalized training programs (“Services”). The Services include:
AI-generated periodized training programs tailored to each athlete's sport, position, and training history;
Session logging, progress tracking, and estimated 1-rep max calculations;
AI-generated coaching responses and exercise recommendations;
Automated video form review using AI image analysis; and
A coach dashboard for enrolled coaching staff.
4.1 AI Disclaimer
Training programs, coaching responses, and all other recommendations generated by the Platform are produced using artificial intelligence technology. AI-generated content is not a substitute for professional coaching, medical advice, physical therapy, or individualized professional guidance. Wilco does not warrant the accuracy, completeness, or suitability of AI-generated content for any specific individual. The appropriateness of any program depends in part on the accuracy of the information you provide. You assume full responsibility for evaluating AI-generated content before acting on it.
5. Free Trial
New users may be eligible for a 7-day free trial. Your free trial begins on the date you create an account and provide valid payment information. You will not be charged during the trial period. At the conclusion of the 7-day trial, your account will automatically convert to a paid subscription at the applicable rate unless you cancel before the trial ends. Each person is entitled to one free trial. Creating multiple accounts to access additional free trials is a material violation of these Terms and may result in account termination.
6. Subscription Terms
6.1 Plans
Wilco offers two individual subscription plans:
Monthly Plan: Billed on a recurring monthly basis.
Annual Plan: Billed annually in advance.
Current pricing for each plan is displayed at checkout. Wilco reserves the right to modify pricing upon 30 days' advance written notice as described in Section 25.
6.2 Automatic Renewal
All subscriptions renew automatically. Monthly Plans renew each month on the same calendar day the subscription began. Annual Plans renew each year on the same calendar date. By subscribing, you authorize Wilco to charge your payment method on file at the then-current rate for each renewal period until you cancel. THE AUTO-RENEWAL TERMS, INCLUDING THE RENEWAL DATE AND THEN-CURRENT RATE, ARE DISCLOSED CLEARLY AND CONSPICUOUSLY AT CHECKOUT PRIOR TO PURCHASE.
6.3 Cancellation
You may cancel your subscription at any time through your account settings or by contacting support@trainwilco.com.
Monthly Plan: Cancellation takes effect at the end of the current billing period. You retain full access through the end of the period already paid. No future charges will be assessed.
Annual Plan: If you cancel an Annual Plan, you are eligible for a partial refund equal to 50% of the value of your remaining full subscription months at the time of cancellation. For example, if 6 full months remain at cancellation, you will receive a refund equal to 3 months of the then-current equivalent monthly rate. No refund is provided for the current or any partial months.
6.4 Refund Policy
All sales are final except as expressly provided in Section 6.3 for Annual Plan cancellations. Monthly Plan fees are non-refundable under any circumstances. If you believe you were charged in error, contact support@trainwilco.com within 30 days of the charge for review.
7. Account Registration and Responsibilities
You are solely responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to:
Provide accurate, current, and complete information during registration and profile setup;
Keep your account information current and accurate at all times;
Notify Wilco immediately of any suspected unauthorized access to your account; and
Not share, sell, or transfer your account credentials to any other person.
Providing inaccurate or incomplete profile information may result in AI-generated training programs that are not appropriate for your physical condition. You assume all risk arising from the submission of inaccurate information.
8. Health Information
The Platform may invite you to provide optional health information, including prior injuries, physical limitations, or known medical conditions. Providing this information is entirely voluntary. When provided, health information is used solely to personalize your AI-generated training programs and is not disclosed to third parties for marketing or commercial purposes. For a complete description of our data practices, review our Privacy Policy at TrainWilco.com/privacy.
9. Medical Disclaimer
THE SERVICES ARE NOT A MEDICAL PRODUCT AND DO NOT CONSTITUTE MEDICAL ADVICE, DIAGNOSIS, OR TREATMENT. THE PLATFORM DOES NOT DIAGNOSE, TREAT, CURE, OR PREVENT ANY PHYSICAL INJURY, ILLNESS, OR MEDICAL CONDITION. BEFORE BEGINNING ANY STRENGTH AND CONDITIONING PROGRAM, INCLUDING ANY PROGRAM GENERATED BY THE PLATFORM, YOU SHOULD CONSULT A LICENSED PHYSICIAN OR QUALIFIED HEALTHCARE PROFESSIONAL, PARTICULARLY IF YOU HAVE A KNOWN MEDICAL CONDITION, PRIOR INJURY, OR OTHER PHYSICAL LIMITATION. WILCO ASSUMES NO LIABILITY ARISING FROM YOUR FAILURE TO OBTAIN APPROPRIATE MEDICAL CLEARANCE PRIOR TO USE OF THE SERVICES.
10. Assumption of Risk and Liability Waiver
10.1 Inherent Risks of Physical Activity
Strength and conditioning training involves inherent and unavoidable risks, including but not limited to: muscle strains, ligament and tendon injuries, joint injuries, stress fractures, cardiovascular stress, overexertion, heat illness, and in rare cases, permanent disability or death. These risks exist regardless of the quality or specificity of the training program followed.
10.2 Voluntary Assumption of Risk
By using the Platform and following any training program generated or accessed through it, you voluntarily and knowingly acknowledge and accept all inherent risks associated with strength and conditioning training. You acknowledge that you are participating of your own free will, that no training program can guarantee freedom from injury, and that the suitability of any AI-generated program depends in part on physical and medical factors that the Platform is unable to independently assess.
10.3 Release of Liability
TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, YOU, ON BEHALF OF YOURSELF AND YOUR HEIRS, NEXT OF KIN, PERSONAL REPRESENTATIVES, AND ASSIGNS, HEREBY IRREVOCABLY RELEASE, WAIVE, DISCHARGE, AND HOLD HARMLESS WILCO TRAINING LLC, ITS MEMBERS, MANAGERS, OFFICERS, EMPLOYEES, AGENTS, INDEPENDENT CONTRACTORS, AND SUCCESSORS (COLLECTIVELY, “RELEASED PARTIES”) FROM ANY AND ALL CLAIMS, LIABILITIES, DEMANDS, ACTIONS, AND CAUSES OF ACTION OF ANY KIND OR NATURE, WHETHER KNOWN OR UNKNOWN, ANTICIPATED OR UNANTICIPATED, ARISING OUT OF OR IN ANY WAY CONNECTED WITH YOUR USE OF THE PLATFORM, INCLUDING ANY PHYSICAL INJURY, ILLNESS, DEATH, PROPERTY DAMAGE, OR OTHER LOSS OR HARM SUSTAINED WHILE FOLLOWING, ATTEMPTING TO FOLLOW, OR OTHERWISE IN CONNECTION WITH A TRAINING PROGRAM GENERATED BY OR ACCESSED THROUGH THE PLATFORM.
Note: Under Florida law (Kirton v. Fields, 2008), pre-injury liability waivers executed by parents on behalf of minor children may not be enforceable for commercial activities. Wilco maintains this waiver to the fullest extent permitted by applicable law. Users in jurisdictions that limit or prohibit such waivers remain subject to all other terms of this Agreement.
10.4 Covenant Not to Sue
You expressly agree that you will not initiate, file, or maintain any lawsuit, arbitration, claim, or legal proceeding of any kind against the Released Parties for any injury, illness, death, property damage, or other loss arising from your use of the Platform or your participation in any training program generated or accessed through the Platform, to the fullest extent permitted by applicable law.
10.5 Parental and Guardian Acknowledgment for Minor Users
IF THE USER IS BETWEEN 13 AND 17 YEARS OF AGE, A PARENT OR LEGAL GUARDIAN MUST COMPLETE THE PARENTAL CONSENT ACKNOWLEDGMENT AT SIGN-UP. THE PLATFORM'S SIGN-UP FLOW USES DATE OF BIRTH VERIFICATION TO IDENTIFY MINOR USERS. WHEN A DATE OF BIRTH INDICATING AN AGE BETWEEN 13 AND 17 IS ENTERED, A SEPARATE PARENTAL CONSENT CHECKBOX IS DISPLAYED ON THE SAME SIGN-UP SCREEN AND MUST BE AFFIRMATIVELY CHECKED BEFORE ACCOUNT CREATION IS PERMITTED. BY CHECKING THAT BOX, THE PARENT OR LEGAL GUARDIAN REPRESENTS AND WARRANTS THAT THEY: (A) ARE THE LEGAL PARENT OR GUARDIAN OF THE MINOR USER; (B) HAVE READ AND FULLY UNDERSTAND THESE TERMS, INCLUDING THE LIABILITY WAIVER IN SECTION 10; (C) CONSENT TO THE MINOR USER'S ACCESS TO AND USE OF THE PLATFORM; AND (D) AGREE TO THE ASSUMPTION OF RISK AND RELEASE OF LIABILITY IN SECTIONS 10.2 AND 10.3 ON BEHALF OF THE MINOR USER AND THEMSELVES.
11. Limitation of Liability
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL WILCO TRAINING LLC BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, EXEMPLARY, OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE PLATFORM, INCLUDING BUT NOT LIMITED TO LOSS OF DATA, LOSS OF PROFITS, LOSS OF GOODWILL, OR BUSINESS INTERRUPTION, EVEN IF WILCO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
IN ALL CASES, WILCO'S TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY AND ALL CLAIMS ARISING UNDER OR RELATED TO THESE TERMS SHALL NOT EXCEED THE TOTAL AMOUNT PAID BY YOU TO WILCO IN THE TWELVE (12) CALENDAR MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
12. Disclaimer of Warranties
THE PLATFORM IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, RELIABILITY, TITLE, OR NON-INFRINGEMENT. WILCO DOES NOT WARRANT THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, SECURE, OR FREE OF HARMFUL COMPONENTS. YOUR USE OF THE PLATFORM IS ENTIRELY AT YOUR OWN RISK.
13. Indemnification
You agree to defend, indemnify, and hold harmless Wilco Training LLC and the Released Parties from and against any and all third-party claims, demands, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or relating to: (a) your use of the Platform; (b) your violation of any provision of these Terms; (c) your breach of any representation or warranty made herein; or (d) your infringement of any intellectual property rights or other rights of any third party.
14. Intellectual Property
All content on the Platform — including but not limited to training programs, AI models, software, text, graphics, logos, and the underlying coaching methodology — is owned by or licensed to Wilco Training LLC and is protected by applicable United States and international intellectual property laws.
You are granted a limited, personal, non-exclusive, non-transferable, revocable license to access and use the Platform solely for your own personal, non-commercial purposes. You may not copy, reproduce, modify, distribute, publicly display, sublicense, sell, or create derivative works from any Platform content without the prior express written consent of Wilco Training LLC.
15. User Content
By submitting content to the Platform — including session logs, performance data, video footage, and optional health information — you grant Wilco a limited, non-exclusive, royalty-free license to store, process, and use that content: (a) as necessary to provide and maintain the Services; and (b) in de-identified, aggregated form to improve and train the AI systems that power the Platform. De-identified data cannot reasonably be used to identify you individually. You retain ownership of your personal data. Wilco will not sell your personal data to third parties.
16. Third-Party Services
The Platform utilizes third-party service providers, including Anthropic PBC (AI processing), Supabase (data infrastructure), Vercel, Inc. (platform hosting), and Stripe, Inc. (payment processing). Your use of the Platform is subject to the applicable terms and privacy policies of these providers. Wilco is not responsible for the acts, omissions, errors, or policies of any third-party service provider.
17. Prohibited Use
You agree not to:
Use the Platform for any unlawful purpose or in violation of any applicable federal, state, or local law or regulation;
Create multiple accounts for the purpose of circumventing free trial limitations or account suspensions;
Share, sell, or transfer your account credentials to any other person;
Reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code or underlying methodology of the Platform;
Copy, reproduce, or distribute any Platform content, training programs, or coaching methodology for commercial purposes;
Submit false, misleading, or inaccurate information during registration or use of the Platform;
Interfere with, disrupt, or damage the Platform or its underlying infrastructure; or
Use the Platform in any manner that could harm, harass, or collect information about other users.
18. Export Controls
The Platform is operated from the United States and is subject to U.S. export control laws and regulations. By using the Platform, you represent that you are not located in, under the control of, or a national or resident of any country subject to U.S. trade sanctions or export restrictions, including Cuba, Iran, North Korea, Russia, Syria, or the Crimea region of Ukraine. Users in sanctioned territories are not authorized to use the Platform.
19. DMCA and Copyright Policy
The Platform permits users to upload video and image content. Wilco respects intellectual property rights and complies with the Digital Millennium Copyright Act (“DMCA”). If you believe that content on the Platform infringes your copyright, submit a written notification to Wilco’s designated DMCA agent at support@trainwilco.com. Your notice must include: (a) a physical or electronic signature of the copyright owner or authorized person; (b) identification of the copyrighted work claimed to have been infringed; (c) identification of the material alleged to be infringing and its location on the Platform; (d) your contact information; (e) a statement that you have a good faith belief that the use is not authorized; and (f) a statement, under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on their behalf. Wilco will respond to valid DMCA notices promptly and will disable access to allegedly infringing content pending investigation.
20. Termination
Wilco reserves the right to suspend or terminate your account at any time, with or without prior notice, for violation of these Terms or for any conduct Wilco, in its sole discretion, determines to be harmful to its users, business, or platform integrity. Upon termination, your license to use the Platform immediately and automatically terminates. You may also close your account at any time through your account settings. The following sections survive termination: 10, 11, 12, 13, 14, 15, 19, 22, and 23.
21. Data Retention
Upon account cancellation or deletion, your personal data will be retained for 30 days to allow for account reactivation. After 30 days, your data will be permanently and irreversibly deleted from our systems, subject to applicable legal retention obligations. To request immediate deletion prior to the 30-day period, contact support@trainwilco.com.
22. Binding Arbitration and Class Action Waiver
PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS BY REQUIRING INDIVIDUAL ARBITRATION OF DISPUTES AND WAIVING YOUR RIGHT TO A JURY TRIAL AND TO PARTICIPATE IN CLASS ACTIONS.
22.1 Agreement to Arbitrate
Except for disputes that qualify for small claims court, you and Wilco agree that any dispute, claim, or controversy arising out of or relating to these Terms or your use of the Platform — including any dispute regarding the scope or enforceability of this arbitration agreement — shall be resolved exclusively through final and binding individual arbitration administered by the American Arbitration Association (“AAA”) under its Consumer Arbitration Rules then in effect, rather than in court. The Federal Arbitration Act governs the interpretation and enforcement of this Section.
22.2 Class Action Waiver
YOU AND WILCO EACH AGREE THAT CLAIMS AGAINST THE OTHER MAY ONLY BE BROUGHT IN YOUR OR ITS INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, COLLECTIVE, CONSOLIDATED, OR REPRESENTATIVE ACTION. THE ARBITRATOR MAY NOT CONSOLIDATE MORE THAN ONE PERSON'S CLAIMS AND MAY NOT PRESIDE OVER ANY FORM OF REPRESENTATIVE OR CLASS PROCEEDING. IF THIS CLASS ACTION WAIVER IS FOUND UNENFORCEABLE FOR ANY CLAIM, THIS ENTIRE SECTION 22 SHALL BE VOID AS TO THAT CLAIM.
22.3 Small Claims Exception
Either party may bring an individual action in small claims court for disputes within that court's jurisdictional limits, provided the action remains in small claims court and is not appealed to a court of general jurisdiction.
22.4 Opt-Out
You may opt out of this arbitration agreement by sending written notice to support@trainwilco.com within 30 days of first creating your account. Your notice must include your full name and a clear statement that you wish to opt out of arbitration. If you opt out, disputes will be resolved exclusively in the courts identified in Section 23.
22.5 Injunctive Relief
Notwithstanding the foregoing, either party may seek emergency injunctive or other equitable relief in a court of competent jurisdiction to protect intellectual property rights or confidential information pending resolution of a dispute through arbitration.
23. Governing Law
These Terms are governed by and shall be construed in accordance with the laws of the State of Florida, without regard to its conflict of law provisions. Any legal proceedings not subject to arbitration under Section 22 shall be brought exclusively in the state or federal courts of competent jurisdiction located in Seminole County, Florida. You irrevocably consent to the personal jurisdiction of those courts and waive any objection to venue therein.
24. Dispute Resolution — Informal Process
Prior to initiating arbitration or any legal proceeding, both parties agree to attempt informal resolution. To initiate this process, contact Wilco at support@trainwilco.com with a written description of the dispute and your requested remedy. Wilco will respond within 15 business days. If the dispute is not resolved within 30 days of first written contact, either party may pursue available remedies including arbitration as provided in Section 22.
25. Changes to These Terms
Wilco reserves the right to update or modify these Terms at any time. We will provide notice of material changes via email and/or a prominent notice on the Platform no fewer than 14 days before the updated Terms take effect. Your continued use of the Platform after the stated effective date constitutes your acceptance of the updated Terms. If you do not agree, you must cancel your subscription and discontinue use before the effective date.
26. Severability
If any provision of these Terms is found by a court of competent jurisdiction to be invalid, illegal, or unenforceable, that provision will be limited or eliminated to the minimum extent necessary so that the remaining provisions remain in full force and effect.
27. Entire Agreement
These Terms, together with Wilco’s Privacy Policy at TrainWilco.com/privacy, constitute the entire agreement between you and Wilco Training LLC with respect to the Platform and supersede all prior or contemporaneous communications, representations, and agreements, whether oral or written.
28. Contact Information
Wilco Training LLC801 International Pkwy, Suite #5034, Lake Mary, Florida 32746TrainWilco.com  |  support@trainwilco.com

BY CHECKING THE BOX BELOW, YOU CONFIRM THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE LEGALLY BOUND BY THESE TERMS OF SERVICE AND LIABILITY WAIVER.

[ ]  I have read and agree to the Wilco Training Terms of Service and Liability Waiver.

If you are under 18, your parent or legal guardian must also check the box below before your account is created:

[ ]  I am the parent or legal guardian of the minor user. I have read and understood these Terms in full, including the Liability Waiver, and I consent to the minor’s use of the Platform on the terms stated herein.

Wilco Training LLC  |  TrainWilco.com  |  support@trainwilco.com801 International Pkwy, Suite #5034, Lake Mary, Florida 32746`;

export const PRIVACY_TEXT = `WILCO TRAINING LLC
Privacy Policy
Effective Date: May 22, 2026  |  Last Updated: June 1, 2026
Wilco Training LLC (“Wilco,” “we,” “us,” or “our”) is committed to protecting the privacy of all users of the Wilco Training platform (“Platform”), including athletes, coaches, and school administrators. This Privacy Policy explains what information we collect, how we use it, how we protect it, and what choices you have. By using the Platform, you agree to the practices described in this Privacy Policy.
This Privacy Policy applies to the Platform operated at TrainWilco.com and all associated web and mobile applications.
1. Information We Collect
1.1 Information You Provide Directly
When you create an account and use the Platform, we collect information you provide, including:
Account information: full name, email address, date of birth, and password;
Athletic profile: sport, position, height, weight, and training history (including estimated 1-rep maxes and prior performance data);
Session data: workout logs, sets, reps, weights, notes, and coach feedback submitted through the Platform;
Optional health information: prior injuries, physical limitations, or medical conditions you choose to disclose to personalize your training programs; and
Video and image submissions: footage or still frames you upload for form review analysis.
1.2 Information Collected Automatically
When you use the Platform, we automatically collect certain technical and usage data, including:
Device type, operating system, and browser information;
IP address and general geographic location;
Pages visited, features used, and time spent on the Platform; and
Session identifiers and authentication tokens.
This information is used to operate and improve the Platform and does not identify you personally on its own.
1.3 Payment Information
Payment transactions are processed by Stripe, Inc., our third-party payment processor. Wilco does not collect, store, or have access to your full credit card number, bank account number, or other sensitive financial data. Stripe’s handling of your financial information is governed by Stripe’s Privacy Policy, available at stripe.com/privacy.
1.4 Analytics and Tracking Technologies
We may use analytics tools and similar technologies to collect information about how users interact with the Platform. This may include cookies, pixel tags, and similar tracking technologies that collect aggregate information about device usage and Platform interaction. You may disable certain cookies through your browser settings, though doing so may affect some Platform features. We do not respond to “Do Not Track” browser signals at this time, as no uniform industry standard has been established.
2. How We Use Your Information
We use the information we collect to provide, maintain, and improve the Platform. Specifically, we use your information to:
Generate personalized, AI-powered strength and conditioning training programs based on your athletic profile and history;
Power the AI coaching assistant and provide exercise recommendations and form feedback;
Track your progress over time and display performance data within your account;
Enable your coach or institution’s coaching staff to access your session data, progress reports, and AI coaching interactions through the coach dashboard;
Process subscription payments and manage your account;
Send essential service communications, including account confirmations, subscription updates, and policy changes;
Respond to your support inquiries and resolve disputes;
Analyze aggregate, de-identified usage patterns to improve Platform features and AI model performance; and
Improve and train our AI systems using de-identified, aggregated data derived from Platform usage. This data cannot reasonably be used to identify you individually.
We do not use your personal data for targeted advertising and do not sell your personal data to third parties under any circumstances.
3. How We Share Your Information
3.1 With Coaching Staff and Institutions
If you are an athlete enrolled under a school or coach account, your session data, progress reports, AI coaching interactions, and form review feedback are visible to the coaching staff authorized under that account. This sharing is a core function of the Platform and is necessary to deliver the Services.
3.2 With Third-Party Service Providers
We share your data with a limited set of vetted third-party service providers who help us operate the Platform. These providers are contractually prohibited from using your data for any purpose other than providing services to Wilco. Our current service providers include:
Anthropic PBC — AI processing and language model infrastructure. Athlete data submitted to AI coaching features is processed through Anthropic’s systems, governed by Anthropic’s Privacy Policy at anthropic.com/privacy.
Supabase — Secure cloud database and authentication infrastructure.
Vercel, Inc. — Platform hosting and content delivery.
Stripe, Inc. — Payment processing, governed by Stripe’s Privacy Policy at stripe.com/privacy.
We do not share your personal data with any other third parties without your explicit consent, except as required by law.
3.3 Legal Disclosures
We may disclose your information if required to do so by law, regulation, legal process, or governmental request, or if we believe in good faith that disclosure is necessary to: (a) comply with a legal obligation; (b) protect the safety of any person; or (c) protect the rights, property, or safety of Wilco Training LLC.
3.4 Business Transfers
In the event that Wilco Training LLC is acquired, merged, or undergoes a substantial asset transfer, your information may be transferred as part of that transaction. We will provide notice of any such change and applicable choices you may have in accordance with applicable law.
4. Data Retention
We retain your personal data for as long as your account is active and for a period of 30 days following account cancellation or deletion. During this 30-day window, you may reactivate your account and recover your data. After 30 days, all personal data associated with your account is permanently and irreversibly deleted from our systems.
Aggregate, de-identified data that cannot reasonably be used to identify you may be retained indefinitely for the purpose of improving the Platform.
Wilco retains certain records as required by applicable law, including financial transaction records, which may be retained beyond the 30-day period in accordance with legal requirements.
5. Your Rights and Choices
You have the following rights with respect to your personal data:
Access: You may request a copy of the personal data we hold about you.
Correction: You may request that we correct inaccurate or incomplete personal data in your account.
Deletion: You may request deletion of your account and associated personal data by contacting us or using the account deletion option in your account settings. Deletion requests are processed within 30 days, subject to applicable legal retention obligations.
Opt-Out of Communications: You may opt out of non-essential marketing communications at any time via the unsubscribe link in any marketing email or by contacting us directly. Essential service communications — including billing notices, subscription changes, and Terms updates — cannot be opted out of while your account remains active.
To exercise any of these rights, contact us at support@trainwilco.com. We will respond within 30 days of receipt. We may request verification of your identity before fulfilling any request.
6. Children’s Privacy
The Platform is intended for users who are at least 13 years of age. Wilco does not knowingly collect personal data from children under 13. If you are a parent or guardian and believe your child under the age of 13 has created an account without your consent, contact us immediately at support@trainwilco.com and we will promptly delete the account and all associated data.
For users between the ages of 13 and 17, the Platform’s sign-up flow uses date of birth verification to identify minor users. When a user’s date of birth indicates an age between 13 and 17, the sign-up screen displays a separate, clearly labeled parental consent acknowledgment checkbox that must be affirmatively checked before account creation is permitted. By checking that box, the parent or legal guardian confirms that they have reviewed this Privacy Policy and the Terms of Service and consent to the data practices described herein on behalf of the minor user.
We encourage parents and guardians of minor users to review this Privacy Policy periodically and to monitor their child’s use of the Platform.
7. Video and Image Data
When you submit video footage or images for form review, the Platform extracts still frames from your submission for automated AI analysis. Wilco does not manually review your video footage; analysis is performed automatically. Still frames are used only during the processing period to generate your form feedback and are not retained or used for any other purpose.
Wilco does not collect, store, or derive biometric identifiers or biometric information — including facial geometry, voiceprints, or similar identifiers — from video or image submissions. Still frames are used solely for motion and athletic form analysis within the context of the Services.
Wilco does not share, sell, or publicly display any user video or image content. Video submissions of minor users are subject to the same protections as all other personal data described in this Policy.
8. Data Security
Wilco implements industry-standard technical and organizational security measures designed to protect your personal data against unauthorized access, loss, alteration, or destruction. These measures include encrypted data transmission, access controls, and secure cloud infrastructure maintained by our service providers.
No security system is impenetrable. In the event of a data breach involving your personal data, Wilco will notify affected users in accordance with applicable law, including within 30 days of determining that a breach has occurred as required under the Florida Information Protection Act (Fla. Stat. § 501.171).
You are responsible for maintaining the confidentiality of your account credentials. Use a strong, unique password and notify us immediately at support@trainwilco.com if you suspect unauthorized access to your account.
9. Third-Party Links
The Platform may contain links to third-party websites or services. This Privacy Policy does not apply to those third-party sites. Wilco is not responsible for the privacy practices or content of third-party websites. We encourage you to review the privacy policies of any third-party services you access through the Platform.
10. Changes to This Privacy Policy
Wilco reserves the right to update this Privacy Policy at any time. We will notify you of material changes by posting the updated Policy on the Platform and by sending a notice to your registered email address at least 14 days before the changes take effect. Your continued use of the Platform after the effective date of any updated Policy constitutes your acceptance of the changes.
The “Last Updated” date at the top of this Policy reflects when the most recent version was published. We encourage you to review this Policy periodically.
11. Contact Us
If you have questions, concerns, or requests related to this Privacy Policy or our data practices, please contact us:
Wilco Training LLC801 International Pkwy, Suite #5034Lake Mary, Florida 32746TrainWilco.com  |  support@trainwilco.com
We will respond to all privacy-related inquiries within 30 days of receipt.
12. Additional Rights for Users in the European Economic Area and United Kingdom
If you are located in the European Economic Area (“EEA”) or the United Kingdom (“UK”), the General Data Protection Regulation (“GDPR”) and, where applicable, the UK GDPR provide you with additional rights and impose additional obligations on Wilco regarding the processing of your personal data.
12.1 Legal Basis for Processing
We process your personal data on the following legal bases:
Contract Performance (Article 6(1)(b)): Processing necessary to deliver the Services you subscribed to, including generating training programs, processing payments, and maintaining your account.
Legitimate Interests (Article 6(1)(f)): Processing for our legitimate interests in operating and improving the Platform, preventing fraud, and ensuring security, where those interests are not overridden by your fundamental rights.
Legal Obligation (Article 6(1)(c)): Processing required to comply with applicable law, including financial record retention and responding to lawful governmental requests.
Consent (Article 6(1)(a)): Where we rely on consent — including for optional health information and for AI improvement uses — you may withdraw consent at any time without affecting the lawfulness of prior processing.
For special category data (health information you voluntarily provide), we rely on your explicit consent under Article 9(2)(a) GDPR.
12.2 Additional Data Subject Rights
In addition to the rights in Section 5, EEA and UK users have the right to:
Data Portability: Receive a copy of your personal data in a structured, machine-readable format for transfer to another controller, where processing is based on consent or contract performance.
Restrict Processing: Request that we restrict processing of your personal data in certain circumstances, such as while a correction request is pending.
Object: Object to processing based on our legitimate interests at any time. We will cease processing unless we demonstrate compelling legitimate grounds that override your interests.
Lodge a Complaint: Lodge a complaint with your local supervisory authority. In the EU, contact the supervisory authority in your country of residence. In the UK, contact the Information Commissioner’s Office (ICO) at ico.org.uk.
To exercise these rights, contact us at support@trainwilco.com. We will respond within one calendar month as required by GDPR.
12.3 International Data Transfers
The Platform is operated from the United States. If you are located in the EEA or UK, your personal data will be transferred to and processed in the United States. Where required by GDPR or UK GDPR, we rely on Standard Contractual Clauses approved by the European Commission (or the applicable UK equivalent) as the legal mechanism for such transfers. For more information, contact us at support@trainwilco.com.
12.4 Retention for EEA and UK Users
In addition to the retention periods in Section 4, EEA and UK users’ personal data is retained only as long as necessary for the purposes for which it was collected, consistent with the legal bases in Section 12.1. We review retention periods periodically.
13. Additional Rights for California Residents
If you are a California resident, the California Consumer Privacy Act (“CCPA”) as amended by the California Privacy Rights Act (“CPRA”) grants you the following additional rights.
13.1 Categories of Personal Information Collected
In the preceding 12 months, we have collected the following categories of personal information as defined under the CCPA:
Identifiers: name, email address, IP address, account credentials, and device identifiers;
Personal information under Cal. Civil Code § 1798.80: name and general location;
Internet or electronic network activity: pages visited, features used, session data, and interaction logs;
Geolocation data: general geographic location derived from IP address;
Inferences: training program recommendations derived from your athletic profile; and
Sensitive personal information: health information you voluntarily provide (injuries, medical conditions); and financial data processed by Stripe, Inc. on our behalf.
13.2 No Sale or Sharing
Wilco does not sell your personal information. Wilco does not share your personal information with third parties for cross-context behavioral advertising. You have the right to opt out of any such sale or sharing; to exercise this right, contact us at support@trainwilco.com (though no sale or sharing currently occurs).
13.3 Your CCPA/CPRA Rights
In addition to the rights in Section 5, California residents have the right to:
Know the categories and specific pieces of personal information collected, the sources, the business purpose, and the third parties with whom it is shared;
Delete personal information we hold about you, subject to certain legal exceptions;
Correct inaccurate personal information;
Opt out of sale or sharing (not currently applicable);
Limit use of sensitive personal information to what is necessary to provide the Services; and
Non-Discrimination: We will not deny Services, charge different prices, or provide a different quality of service because you exercised any CCPA/CPRA right.
Contact us at support@trainwilco.com to exercise your rights. We will verify your identity and respond within 45 days, extendable by 45 additional days with notice.
13.4 Authorized Agent
You may designate an authorized agent to submit requests on your behalf by providing written signed authorization. We may verify your identity directly before honoring such requests.
14. International Users and Export Controls
The Platform is operated from the United States and is subject to U.S. export control laws. By using the Platform, you represent that you are not located in, under the control of, or a national or resident of any country subject to U.S. trade sanctions or export restrictions, including Cuba, Iran, North Korea, Russia, Syria, or the Crimea region of Ukraine. Users in sanctioned territories are not authorized to use the Platform.

Wilco Training LLC  |  TrainWilco.com  |  support@trainwilco.com801 International Pkwy, Suite #5034, Lake Mary, Florida 32746`;

// Whole years between a birthday (ISO/date string) and now. Mirrors the age math
// used in SignupScreen.createAthlete so the minor branch stays consistent.
export const ageFromBirthday = (birthday) => {
  if (!birthday) return null;
  const dob = new Date(birthday);
  if (isNaN(dob.getTime())) return null;
  return Math.floor((Date.now() - dob) / (365.25 * 24 * 60 * 60 * 1000));
};

// A "minor" per the Terms (§10.5) / Privacy Policy (§6): 13–17 inclusive. Under 13
// is already blocked earlier in onboarding, so this is effectively "under 18".
export const isMinorBirthday = (birthday) => {
  const a = ageFromBirthday(birthday);
  return a !== null && a >= 13 && a < 18;
};

const localBtn = (bg, color, extra = {}) => ({
  background: bg, color, border: "none", borderRadius: 12, padding: "14px",
  fontWeight: 700, fontSize: 16, cursor: "pointer", width: "100%",
  fontFamily: "'Bebas Neue'", letterSpacing: 2, ...extra,
});

// Render a document: title lines as gold headers, "N." / "N.N" lines as section
// headings, everything else as readable body paragraphs.
function LegalDocBody({ C, text }) {
  const lines = text.split("\n");
  return (
    <div>
      {lines.map((ln, i) => {
        const t = ln.trim();
        if (!t) return <div key={i} style={{ height: 8 }} />;
        const isTitle = /^(WILCO TRAINING LLC|Terms of Service and Liability Waiver|Privacy Policy)$/.test(t);
        const isEffective = /^Effective Date:/.test(t);
        const isSection = /^\d+(\.\d+)*\.?\s+\S/.test(t);
        if (isTitle) return <div key={i} style={{ color: C.gold, fontFamily: "'Bebas Neue'", fontSize: 20, letterSpacing: 1, marginTop: i ? 16 : 0, marginBottom: 4 }}>{t}</div>;
        if (isEffective) return <div key={i} style={{ color: C.muted2, fontSize: 12, marginBottom: 10 }}>{t}</div>;
        if (isSection) return <div key={i} style={{ color: C.text, fontWeight: 700, fontSize: 14, marginTop: 14, marginBottom: 4 }}>{t}</div>;
        return <p key={i} style={{ color: C.muted2, fontSize: 13, lineHeight: 1.7, marginBottom: 8 }}>{t}</p>;
      })}
    </div>
  );
}

// Short explanatory body for the parental-consent gate (no document text).
function ParentalBody({ C }) {
  return (
    <div style={{ color: C.muted2, fontSize: 14, lineHeight: 1.7 }}>
      <p style={{ marginBottom: 12 }}>
        Because you are under 18, a parent or legal guardian must consent to these
        terms on your behalf before your account can be created.
      </p>
      <p style={{ marginBottom: 12 }}>
        On the next screens you'll review WILCO's Terms of Service & Liability Waiver
        and Privacy Policy. By continuing, your parent or guardian confirms they have
        read and agreed to those documents on your behalf, including the liability
        waiver.
      </p>
    </div>
  );
}

// One full-screen consent step: scrollable content + a required checkbox gating
// the primary button, plus an always-active "Decline & Go Back".
export function LegalModal({ C, kicker, title, text, parental, checkboxLabel, primaryLabel, onAccept, onDecline, busy }) {
  const [checked, setChecked] = useState(false);
  const canContinue = checked && !busy;
  return (
    <div style={{ position: "fixed", inset: 0, zIndex: 1000, background: C.navy, display: "flex", flexDirection: "column", maxWidth: 600, margin: "0 auto" }}>
      <div style={{ padding: "calc(16px + env(safe-area-inset-top,0px)) 20px 12px", borderBottom: `1px solid ${C.border}` }}>
        {kicker && <div style={{ color: C.gold, fontFamily: "'Bebas Neue'", fontSize: 13, letterSpacing: 2, marginBottom: 4 }}>{kicker}</div>}
        <div style={{ color: C.text, fontSize: 18, fontWeight: 700 }}>{title}</div>
      </div>
      <div style={{ flex: 1, overflowY: "auto", WebkitOverflowScrolling: "touch", padding: "16px 20px" }}>
        <div style={{ maxWidth: 720, margin: "0 auto" }}>
          {parental ? <ParentalBody C={C} /> : <LegalDocBody C={C} text={text} />}
        </div>
      </div>
      <div style={{ borderTop: `1px solid ${C.border}`, padding: "14px 20px calc(14px + env(safe-area-inset-bottom,0px))", background: C.navy2 }}>
        <label style={{ display: "flex", alignItems: "flex-start", gap: 10, cursor: "pointer", marginBottom: 12 }}>
          <input type="checkbox" checked={checked} onChange={e => setChecked(e.target.checked)} style={{ marginTop: 2, width: 18, height: 18, accentColor: C.gold, flexShrink: 0 }} />
          <span style={{ color: C.text, fontSize: 13, lineHeight: 1.5 }}>{checkboxLabel}</span>
        </label>
        <button onClick={onAccept} disabled={!canContinue} style={localBtn(canContinue ? C.gold : C.navy3, canContinue ? "#000" : C.muted, { opacity: canContinue ? 1 : 0.7, cursor: canContinue ? "pointer" : "not-allowed" })}>
          {busy ? "Please wait..." : primaryLabel}
        </button>
        <button onClick={onDecline} disabled={busy} style={{ background: "none", border: "none", color: C.muted, fontSize: 13, cursor: busy ? "not-allowed" : "pointer", width: "100%", padding: "12px 0 2px", marginTop: 6 }}>
          Decline & Go Back
        </button>
      </div>
    </div>
  );
}

// Orchestrates the consent sequence: parental gate (only for 13–17) → Terms →
// Privacy. onComplete({ isMinor }) fires when every required box is checked and
// the final "Create Account" is tapped. onDecline fires from any step.
// `busy` freezes the final step while the account is being created.
export function ConsentFlow({ C, birthday, busy, onComplete, onDecline }) {
  const minor = isMinorBirthday(birthday);
  const [stage, setStage] = useState(minor ? "parental" : "terms");

  if (stage === "parental") {
    return (
      <LegalModal key="parental" C={C} parental
        kicker="PARENTAL CONSENT REQUIRED"
        title="A parent or guardian must consent"
        checkboxLabel="I confirm that my parent or guardian has read these terms and consents to my use of WILCO Training."
        primaryLabel="Continue →"
        onAccept={() => setStage("terms")}
        onDecline={onDecline}
      />
    );
  }
  if (stage === "terms") {
    return (
      <LegalModal key="terms" C={C} text={TERMS_TEXT}
        kicker="STEP 1 OF 2"
        title="Terms of Service & Liability Waiver"
        checkboxLabel="I have read and agree to the Terms & Conditions."
        primaryLabel="Continue →"
        onAccept={() => setStage("privacy")}
        onDecline={onDecline}
      />
    );
  }
  return (
    <LegalModal key="privacy" C={C} text={PRIVACY_TEXT} busy={busy}
      kicker="STEP 2 OF 2"
      title="Privacy Policy"
      checkboxLabel="I have read and agree to the Privacy Policy."
      primaryLabel="Create Account"
      onAccept={() => onComplete({ isMinor: minor })}
      onDecline={onDecline}
    />
  );
}
